### ISSUE TITLE
Cannot create model

### ISSUE THREAD

**Issue by antithing** [xmba15/torch_cpp#4]
Hi! Thank you for this code. I am trying to convert the model, and i see this error:

Loaded SuperGlue model ("outdoor" weights)
Traceback (most recent call last):
  File "D:\tracking_2022\deepfeatures\torch_cpp-master\scripts\superglue\jit_superglue_model.py", line 17, in <module>
    main()
  File "D:\tracking_2022\deepfeatures\torch_cpp-master\scripts\superglue\jit_superglue_model.py", line 11, in main
    scripted_module = torch.jit.script(superglue)
  File "C:\Users\B\AppData\Roaming\Python\Python39\site-packages\torch\jit\_script.py", line 1257, in script
    return torch.jit._recursive.create_script_module(
  File "C:\Users\B\AppData\Roaming\Python\Python39\site-packages\torch\jit\_recursive.py", line 451, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "C:\Users\B\AppData\Roaming\Python\Python39\site-packages\torch\jit\_recursive.py", line 513, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "C:\Users\B\AppData\Roaming\Python\Python39\site-packages\torch\jit\_script.py", line 587, in _construct
    init_fn(script_module)
  File "C:\Users\B\AppData\Roaming\Python\Python39\site-packages\torch\jit\_recursive.py", line 491, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "C:\Users\B\AppData\Roaming\Python\Python39\site-packages\torch\jit\_recursive.py", line 517, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "C:\Users\B\AppData\Roaming\Python\Python39\site-packages\torch\jit\_recursive.py", line 368, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError:
Can not iterate over a module list or tuple with a value that does not have a statically determinable length
:
  File "D:\tracking_2022\deepfeatures\torch_cpp-master\scripts\superglue\SuperGluePretrainedNetwork\models\superglue.py", line 133
    def forward(self, desc0: torch.Tensor, desc1: torch.Tensor) -> Tuple[torch.Tensor,torch.Tensor]:
        for layer, name in zip(self.layers, self.names):
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            if name == 'cross':
                src0, src1 = desc1, desc0

**Comment by xmba15** [comment]
Hi @antithing 
Did you follow the procedure in [this section](https://github.com/xmba15/torch_cpp#superpoint-and-superglue)? 

I also enclosed the model weights in this release.
https://github.com/xmba15/torch_cpp/releases/tag/0.0.1
